swagger: "2.0"
info:
  title: Dukedoms of Daleria Game Service API
  version: 0.1.0

paths:
  /newGame:
    post:
      summary: create new Game
      x-swagger-router-controller: controllers.game_endpoints
      operationId: create_new_game
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: newGameRequest
          description: request to start process of making new game
          schema:
            type: object
            required:
              - hostPlayer
              - invitedPlayers
            properties:
              hostPlayer:
                type: string
              invitedPlayers:
                type: string
      responses:
        200:
          description: game successfully created
          schema:
            type: object
            properties:
              gameCreated:
                type: boolean
              gameId:
                type: integer
        400:
          description: Bad Request
          schema:
            type: object
            properties:
              gameCreated:
                type: boolean
              reason:
                type: string

  /getGame/{gameId}:
    get:
      x-swagger-router-controller: controllers.game_endpoints
      operationId: get_game_info
      summary: gets game data by its gameId
      parameters:
        - in: path
          name: gameId
          type: integer
          required: true
          description: integer id of a dukedoms game
      produces:
        - application/json
      responses:
        200:
          description: game successfully retrieved
          schema:
            type: object
            properties:
              gameId:
                type: integer
              players:
                type: object
                properties:
                  hostPlayer:
                    type: string
                  invitedPlayers:
                    type: string
              game_state:
                type: string
