swagger: "2.0"
info:
  title: Dukedoms of Daleria Game Service API
  version: 0.2.0

paths:
  /newGame:
    post:
      summary: create new Game
      x-swagger-router-controller: controllers.game_operations
      operationId: create_new_game
      tags:
        - gameOperations
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: newGameRequest
          description: request to start process of making new game
          schema:
            $ref: '#/definitions/NewGameRequest'
      responses:
        200:
          description: game successfully created
          schema:
            $ref: '#/definitions/NewGameSuccessResponse'
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/NewGameFailedResponse'
  /acceptInvite:
    post:
      summary: accept an invite
      x-swagger-router-controller: controllers.game_operations
      operationId: accept_invite
      tags:
        - gameOperations
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: gameInviteAcceptance
          description: data for player accepting the game invite
          required: true
          schema:
            $ref: '#/definitions/InviteResponse'
      responses:
        200:
          description: successfully joined game
          schema:
            $ref: '#/definitions/NewGameWelcomePacket'
  /declineInvite:
    post:
      summary: decline a game invite
      x-swagger-router-controller: controllers.game_operations
      operationId: decline_invite
      tags:
        - gameOperations
      consumes:
        - application/json
      parameters:
        - in: body
          name: gameInviteRejection
          description: data for player rejecting the game invite
          required: true
          schema:
            $ref: '#/definitions/InviteResponse'
      responses:
        200:
          description: successfully declined game

  /getGame/{gameId}:
    get:
      x-swagger-router-controller: controllers.game_info
      operationId: get_game_info
      tags:
        - gameInfo
      summary: gets game data by its gameId
      parameters:
        - in: path
          name: gameId
          type: integer
          required: true
          description: integer id of a dukedoms game
      produces:
        - application/json
      responses:
        200:
          description: game successfully retrieved
          schema:
            $ref: '#/definitions/GameInfo'

definitions:
  InviteResponse:
    type: object
    properties:
      gameId:
        type: integer
      playerEmail:
        type: string
      accountId:
        type: integer
  NewGameWelcomePacket:
    type: object
    properties:
      gameId:
        type: integer
      playerId:
        type: integer
  NewGameRequest:
    type: object
    required:
      - hostPlayer
      - invitedPlayers
    properties:
      hostPlayer:
        type: string
      invitedPlayers:
        type: object
  NewGameSuccessResponse:
      type: object
      properties:
        gameCreated:
          type: boolean
        gameId:
          type: integer
  NewGameFailedResponse:
      type: object
      properties:
        gameCreated:
          type: boolean
        reason:
          type: string
  GameInfo:
    type: object
    properties:
      gameId:
        type: integer
      players:
        type: object
        properties:
          hostPlayer:
            type: string
          invitedPlayers:
            type: object
          acceptedPlayers:
            type: object
          pendingPlayers:
            type: object
          declinedPlayers:
            type: object
      gameState:
        type: string
